#!/usr/bin/env python3
"""
Command line script for the iRacing League Session Auditor
"""

import sys
from iracing_league_session_auditor.cli import main

if __name__ == "__main__":
    sys.exit(main())
